### ISSUE TITLE
Some multiline descriptions change to inline "\n"ed strings

### ISSUE THREAD

**Issue by ReginaldoSantos** [kpramesh2212/openapi-merger-plugin#8]
Plugin version: 1.0.3 (also happens with 1.0.4)

```txt
./gradlew --version

------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.11 (Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OS:           Linux 5.8.0-59-generic amd64
```

openapiOne.yaml
```yaml
openapi: 3.0.1
components:
  schemas:
    IdData:
      type: string
      description: |
        Here comes the problem!
          - every
          - item
          - gets
          - "\n"
          
        Is there a way to overcome this?
          - I hope so
```

openapiTwo.yaml
```yaml
openapi: 3.0.1
components:
  schemas:
    Data:
      type: object
      properties:
        dateField:
          type: string
          description: |
            There is no problem here!
            But I don't know why
          format: date-time
          example: 2021-07-02T08:30:00Z
        stringField:
          type: string
          description: |
            There is no problem here!
            But I don't know why
```
result.yaml

```yaml
openapi: 3.0.1
info:
  title: Test API
  version: 1.0.0
servers:
- url: /
components:
  schemas:
    Data:
      type: object
      properties:
        dateField:
          type: string
          description: |
            There is no problem here!
            But I don't know why
          format: date-time
          example: 2021-07-02T08:30:00Z
        stringField:
          type: string
          description: |
            There is no problem here!
            But I don't know why
    IdData:
      type: string
      description: "Here comes the problem!\n- every\n- item\n- gets\n- \"\\n\"\n\
        \  \nIs there a way to overcome this:\n- I hope so"
```

The problem happen on the description field of schema **IdData**.
It looks like hiphen is responsible for it.
Let me know if you need any more details to dig on that!

**Comment by kpramesh2212** [comment]
@ReginaldoSantos 

For me it seems to work fine.

Can you share me the build.gradle.kts file.


Here is mine


```
plugins {
    java
    id("com.rameshkp.openapi-merger-gradle-plugin") version "1.0.4"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}


openApiMerger {
    inputDirectory.set(file("src/main/java/"))

    output {
        directory.set(buildDir)
        fileName.set("openapi")
        fileExtension.set("yaml")
    }

    openApi {
        openApiVersion.set("3.0.1")
        info {
            title.set("Open API Merger")
            description.set("All files merged by open api merger")
            version.set("1.0.0-SNAPSHOT")
        }
    }
}
```

I am getting the following output

![image](https://user-images.githubusercontent.com/6614973/124788736-8dcfb480-df41-11eb-8e3a-c0bd392f7ca7.png)

**Comment by kpramesh2212** [comment]
@ReginaldoSantos 

kk I think this issue is same as #9 

In your openapiOne.yaml file

![image](https://user-images.githubusercontent.com/6614973/125070816-5fbcb280-e0b0-11eb-9ff4-c71cf772b1ad.png)

Right after last entry in your list item which is escaped newline character("\n") 

There is one non escaped new line character followed by  2 spaces and a non escaped new line character as shown below

```
- "\n"
new line 
space space  
new line
```


The byte code of your description in openapiOne.yaml file (highlighted 2 spaces and the new line character 32, 32, 10)

![image](https://user-images.githubusercontent.com/6614973/125073436-dad39800-e0b3-11eb-8b1b-18410de68653.png)


**So if the last character is a space and a new line character then the string wont be converted into multi line yaml string. Again this is how the core swagger parser and the underlying jackson yaml parser is behaving.**


You can actually stimulate this 

Lets take a following configuration in build.gradle 

**Note: the description field**

![image](https://user-images.githubusercontent.com/6614973/125073732-4ddd0e80-e0b4-11eb-8297-96f21f41d2f8.png)

Now the generated file has a multi line string (Ignore indent thats because of groovy)

![image](https://user-images.githubusercontent.com/6614973/125073932-9268aa00-e0b4-11eb-8265-b1f0020d1326.png)


Now change the description and add a space and newline character at the  end

![image](https://user-images.githubusercontent.com/6614973/125074131-c8a62980-e0b4-11eb-83c7-d554c34fa4ea.png)


Now the generated file doesnt have multi line string

![image](https://user-images.githubusercontent.com/6614973/125074229-e83d5200-e0b4-11eb-8f66-724210b6a598.png)



So the solution is to make sure that space is not the last character followed by new line in the file.

**Comment by ReginaldoSantos** [comment]
@kpramesh2212 you are correct! Issue is the same as #9 

Testing on real documentation I had to apply the following definitions:

1. Cannot use commas (Remove all commas);
2. Remove space after colon;
3. Remove indent space before new line character;

Thank you very much!
